# Run continuous integration
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: false
      - name: Build with Maven
        run: 'mvn clean install'
        shell: bash
      - name: Run tieredconfigurations.PowerMain
        run: 'mvn exec:java -pl modules/cloudsim-green-project/ -Dexec.mainClass=org.cloudbus.cloudsim.tieredconfigurations.PowerMain'
        shell: bash
